# Generated by Django 2.1.3 on 2018-12-30 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('price', models.FloatField(default=0)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.URLField(default='http://www.mysite.com/myimage.png')),
                ('description', models.TextField()),
                ('highscore', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.TextField()),
                ('score', models.PositiveIntegerField(default=0)),
                ('game_state', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_bank_reference', models.TextField(blank=True, max_length=100)),
                ('points_level', models.PositiveIntegerField(default=0)),
                ('inventory', models.ManyToManyField(blank=True, default=None, to='app.Game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Player')),
            ],
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Genre'),
        ),
        migrations.AddField(
            model_name='developer',
            name='inventory',
            field=models.ManyToManyField(blank=True, default=None, to='app.Game'),
        ),
        migrations.AddField(
            model_name='developer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer', to=settings.AUTH_USER_MODEL),
        ),
    ]
