# Generated by Django 2.1.3 on 2019-01-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inventory',
            field=models.ManyToManyField(blank=True, default=None, related_name='users', to='app.Game'),
        ),
    ]
