# Generated by Django 2.1.3 on 2019-01-09 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20190106_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_level', models.PositiveIntegerField(default=0)),
                ('image', models.URLField(default='/static/media/no-image.png')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.FilePathField(default='/static/media/no-image.png'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='inventory',
            field=models.ManyToManyField(blank=True, default=None, to='app.Game'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
