# Generated by Django 2.1.7 on 2019-02-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190217_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dev_games_count',
            field=models.IntegerField(default=0),
        ),
    ]
