# Generated by Django 2.1.3 on 2019-01-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_is_dev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_dev',
        ),
    ]
