# Generated by Django 2.1.7 on 2019-02-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190217_1315'),
        ('app', '0003_user_dev_games_count'),
    ]

    operations = [
    ]
