# Generated by Django 2.1.3 on 2019-01-10 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190110_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='icon',
        ),
    ]
