# Generated by Django 2.1.7 on 2019-02-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20190218_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email',)},
        ),
    ]
