# Generated by Django 2.1.3 on 2019-01-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190113_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name', 'genre']},
        ),
    ]
