# Generated by Django 2.1.3 on 2019-01-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190115_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True, default='https://pngimage.net/wp-content/uploads/2018/05/default-user-profile-image-png-2.png', null=True),
        ),
    ]
