# Generated by Django 2.1.3 on 2019-01-20 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='highscore',
        ),
        migrations.AddField(
            model_name='game',
            name='high_score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='high_score_in', to='app.GameScore'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
