# Generated by Django 2.1.3 on 2019-01-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190120_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestate',
            name='settings',
        ),
    ]
