# Generated by Django 2.1.3 on 2019-01-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190122_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamescore',
            old_name='timestamp',
            new_name='play_date',
        ),
        migrations.RenameField(
            model_name='gamestate',
            old_name='timestamp',
            new_name='save_date',
        ),
    ]
