# Generated by Django 2.1.3 on 2019-01-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190122_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
