# Generated by Django 2.1.3 on 2019-01-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190122_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamescore',
            old_name='date',
            new_name='score_date',
        ),
        migrations.RenameField(
            model_name='gamestate',
            old_name='date',
            new_name='save_date',
        ),
    ]
