# Generated by Django 2.1.3 on 2019-01-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190122_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamescore',
            old_name='score_date',
            new_name='scoreDate',
        ),
        migrations.RenameField(
            model_name='gamestate',
            old_name='game_state',
            new_name='gameState',
        ),
        migrations.RenameField(
            model_name='gamestate',
            old_name='save_date',
            new_name='saveDate',
        ),
    ]
