# Generated by Django 2.1.3 on 2019-01-22 21:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190122_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='scoreDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 21, 5, 31, 339988, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='saveDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 21, 5, 31, 339457, tzinfo=utc)),
        ),
    ]
