# Generated by Django 2.1.3 on 2019-01-22 22:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190122_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='scoreDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 22, 33, 34, 896220, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='saveDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 22, 33, 34, 895691, tzinfo=utc)),
        ),
    ]
