# Generated by Django 2.1.3 on 2019-01-23 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190123_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='scoreDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='saveDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
